---
title: "GRENE_figure1"
author: "Kazuo Isobe and Yaping Liu"
date: "2025-08-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      dev = "png")
```

```{r library,results='hide'}
#library R packages.
library(vegan)
library(ggplot2)
library(ggpmisc)
library(here)
library(tidyverse)
library(dplyr)#rename
library(ggsignif)
library(cowplot)
library(rfPermute)
library(tidyr)
library(gdm)
library(geosphere)
library(plspm) # SEM
library(rstatix)
library(reshape)#melt
library(kableExtra)#output of table
library(linkET)#mantel
library(phyloseq)
library(ggpubr) #stat_compare_means
```

```{r path}
#Use the "here" function to use relative path.
here::here("dataanalysis")
```

```{r get data,base data, microbial data and GDM output data}
# get base data
data_path <- here("dataanalysis/00data/rawdata","ASV-sample.csv")
data_base <- read.csv(data_path)

data_path_38 <- here("dataanalysis/00data","sem_for_alpha2_38.txt")
data_base_38 <- read.csv(data_path_38, header = TRUE, sep = "\t", row.names = 1)

data_path_190 <- here("dataanalysis/00data","sem_beta190.txt")
data_base_190 <- read.csv(data_path_190, header = TRUE, sep = "\t", row.names = 1)

# get microbial data
## bacteria
otu_tab_bac_path <- here("dataanalysis/00data/rawdata","Bac-count.csv")
otu_tab_bac <- read.csv(otu_tab_bac_path,fileEncoding = "UTF-8-BOM")

tax_tab_bac_path <- here("dataanalysis/00data/rawdata","Bac-taxonomy.csv")
tax_tab_bac <- read.csv(tax_tab_bac_path,fileEncoding = "UTF-8-BOM")

## fungi
otu_tab_fung_path <- here("dataanalysis/00data/rawdata","fungi-count.csv")
otu_tab_fung <- read.csv(otu_tab_fung_path,fileEncoding = "UTF-8-BOM")

tax_tab_fung_path <- here("dataanalysis/00data/rawdata","fungi-taxonomy.csv")
tax_tab_fung <- read.csv(tax_tab_fung_path,fileEncoding = "UTF-8-BOM")

# get gdm output
gdm_bac_path <- here("dataanalysis/00data","GRENE_bac_GDM_ispline.txt")
gdm_bac <- read.csv(gdm_bac_path, header = TRUE, sep = "\t", row.names = 1)

gdm_fung_path <- here("dataanalysis/00data","GRENE_fung_GDM_ispline.txt")
gdm_fung <- read.csv(gdm_fung_path, header = TRUE, sep = "\t", row.names = 1)

# get function data
KO_N_path <-  here("dataanalysis/00data","KO_nitrogen_summary_38.txt")
KO_N <- read.csv(KO_N_path, header = TRUE, sep = "\t", row.names = 1)

KO_path <- here("dataanalysis/00data","MAPLE_KO_summary_for_R_38.txt")
KO <- read.csv(KO_path, header = TRUE, sep = "\t")
KO_table <- KO %>%
  group_by(KO) %>%  
  summarise(across(everything(), sum))
KO_table <- data.frame(KO_table)
rownames(KO_table) <- KO_table$KO
KO_table <- KO_table[,-1]

```

```{r import data into phyloseq}
# Import into phyloseq
## Bacteria
row.names(otu_tab_bac) <- otu_tab_bac$OTU
otu_tab_bac <- otu_tab_bac %>% select(-OTU)
row.names(tax_tab_bac) <- tax_tab_bac$OTU
tax_tab_bac <- tax_tab_bac %>% select (-OTU) 
row.names(data_base) <- data_base$sample
samples <- data_base %>% select (-sample)
otu_tab_bac <- as.matrix(otu_tab_bac)  # Transform into matrixes otu and tax tables
tax_tab_bac <- as.matrix(tax_tab_bac)
otu_tab_bac = otu_table(otu_tab_bac, taxa_are_rows = TRUE) # Transform into phyloseq readable format
tax_tab_bac = tax_table(tax_tab_bac)
samples = sample_data(data_base)
physeq_bac <- phyloseq(otu_tab_bac, tax_tab_bac, samples)

## Fungi
row.names(otu_tab_fung) <- otu_tab_fung$OTU
otu_tab_fung <- otu_tab_fung %>% select(-OTU)
row.names(tax_tab_fung) <- tax_tab_fung$OTU
tax_tab_fung <- tax_tab_fung %>% select (-OTU) 
row.names(data_base) <- data_base$sample
samples <- data_base %>% select (-sample)
otu_tab_fung <- as.matrix(otu_tab_fung)    # Transform into matrixes otu and tax tables
tax_tab_fung <- as.matrix(tax_tab_fung)
otu_tab_fung = otu_table(otu_tab_fung, taxa_are_rows = TRUE) # Transform into phyloseq readable format
tax_tab_fung = tax_table(tax_tab_fung)
samples = sample_data(data_base)
physeq_fungi <- phyloseq(otu_tab_fung, tax_tab_fung, samples)

## N cycling
physeq_N <- phyloseq(
  otu_table(KO_N, taxa_are_rows = TRUE),
  sample_data(data_base_38)
)

## KO
## N cycling
physeq_KO <- phyloseq(
  otu_table(KO_table, taxa_are_rows = TRUE),
  sample_data(data_base_38)
)

```


```{r output path}
Figure_path <- "C:/Users/alip/Dropbox/Yaping/GRENE/paper/Revise_submit_20250728/Revise_submit_20250728/RScriptsandFigures/"
```


>**Figure1: Broad-scale factors => Soil properties**

```{r Random forest}
## braod-scale factors
# WRB = "soil patent material"
# Dominant_tree_type = "vegetation"
# Dominant_tree_species = "tree species"
# MAP and MAT = "climate"

## soil properties
# pH.H2O. = "soil habitat pH"
# Total.C = "soil C content"
# Total.N = "soil N content"
# CN = "soil C-to-N"
# FH_C = "litter C content"
# FH_N = "litter N content"
# FH_CN = "litter C-to-N"

set.seed(123)
## Random forest for pH.H2O.
RF_pH <- data_base[,c("pH.H2O.","WRB","Dominant_tree_type","MAP", "MAT")] # this dataset includes only the variables of interest
rfp_pH <- rfPermute(pH.H2O.~., data = RF_pH, importance = TRUE, ntree = 500, nrep = 1000, num.cores = 1)
importance_pH <- data.frame(Variable = rownames(importance(rfp_pH, scale = TRUE)),
                            importance(rfp_pH, scale = TRUE), 
                            heck.names = FALSE)

## Add a new column for asterisk labels based on the p-value condition
importance_pH$label <- ifelse(importance_pH$X.IncMSE.pval < 0.05, "*", "")
print(importance_pH)

## Extract the last value of rfp_pH$rf$rsq, which corresponds to the overall % Var explained
var_explained_pH <- tail(rfp_pH$rf$rsq, 1) * 100
print(var_explained_pH)

## Plot
RF_pH_plot <-
  ggplot(importance_pH, aes(x = reorder(Variable, X.IncMSE), y = X.IncMSE)) +
  geom_bar(stat = "identity", fill = "gray", alpha = 0.8) +
  geom_text(aes(label = label, y = X.IncMSE + 2)) + # add P-value label
  coord_flip() + # Flip coordinates for horizontal bars
  labs(x = "", y = "Increase in MSE (%)", 
       subtitle = paste("Soil pH\nVariation explained:", round(var_explained_pH, 2), "%")) + # add var explained
  theme_classic() +
  theme(axis.title =  element_text(size = 12),
        axis.text = element_text(size = 12),
        plot.subtitle = element_text(size = 12)) + 
  scale_x_discrete(labels = function(x) sapply(x, function(el) {
    if (el == "WRB") return("Soil type")
    else if (el == "Dominant_tree_type") return("Vegetation")
    else return(el)
  })) 
print(RF_pH_plot)

ggsave(paste0(Figure_path,"Figure1B_RF_pH_plot.pdf"),RF_pH_plot,width = 3,height = 4)

## Random forest for soil C content
RF_TC <- data_base[,c("Total.C","WRB","Dominant_tree_type","MAP", "MAT")] # this dataset includes only the variables of interest
rfp_TC <- rfPermute(Total.C~., data = RF_TC, importance = TRUE, ntree = 500, nrep = 1000, num.cores = 1)
importance_TC <- data.frame(Variable = rownames(importance(rfp_TC, scale = TRUE)),
                            importance(rfp_TC, scale = TRUE), 
                            heck.names = FALSE)

## Add a new column for asterisk labels based on the p-value condition
importance_TC$label <- ifelse(importance_TC$X.IncMSE.pval < 0.05, "*", "")
print(importance_TC)

## Extract the last value of rfp_pH$rf$rsq, which corresponds to the overall % Var explained
var_explained_TC <- tail(rfp_TC$rf$rsq, 1) * 100
print(var_explained_TC)

## Plot
RF_TC_plot <-
  ggplot(importance_TC, aes(x = reorder(Variable, X.IncMSE), y = X.IncMSE)) +
  geom_bar(stat = "identity", fill = "gray", alpha = 0.8) +
  geom_text(aes(label = label, y = X.IncMSE + 2)) + # add P-value label
  coord_flip() + # Flip coordinates for horizontal bars
  labs(x = "", y = "Increase in MSE (%)", 
       subtitle = paste("Soil C content/nVariation explained:", round(var_explained_TC, 2), "%")) + # add var explained
  theme_classic() +
  theme(axis.title =  element_text(size = 12),
        axis.text = element_text(size = 12),
        plot.subtitle = element_text(size = 12)) + 
  scale_x_discrete(labels = function(x) sapply(x, function(el) {
    if (el == "WRB") return("Soil type")
    else if (el == "Dominant_tree_type") return("Vegetation")
    else return(el)
  })) 
print(RF_TC_plot)

ggsave(paste0(Figure_path,"Figure1D_RF_TC_plot.pdf"),RF_TC_plot,width = 3,height = 4)

## Random forest for soil N content
RF_TN <- data_base[,c("Total.N","WRB","Dominant_tree_type","MAP", "MAT")] # this dataset includes only the variables of interest
rfp_TN <- rfPermute(Total.N~., data = RF_TN, importance = TRUE, ntree = 500, nrep = 1000, num.cores = 1)
importance_TN <- data.frame(Variable = rownames(importance(rfp_TN, scale = TRUE)),
                            importance(rfp_TN, scale = TRUE), 
                            heck.names = FALSE)
## Add a new column for asterisk labels based on the p-value condition
importance_TN$label <- ifelse(importance_TN$X.IncMSE.pval < 0.05, "*", "")
print(importance_TN)

## Extract the last value of rfp_pH$rf$rsq, which corresponds to the overall % Var explained
var_explained_TN <- tail(rfp_TN$rf$rsq, 1) * 100
print(var_explained_TN)

## Plot
RF_TN_plot <-
  ggplot(importance_TN, aes(x = reorder(Variable, X.IncMSE), y = X.IncMSE)) +
  geom_bar(stat = "identity", fill = "gray", alpha = 0.8) +
  geom_text(aes(label = label, y = X.IncMSE + 2)) + # add P-value label
  coord_flip() + # Flip coordinates for horizontal bars
  labs(x = "", y = "Increase in MSE (%)", 
       subtitle = paste("Soil N content\nVariation explained:", round(var_explained_TN, 2), "%")) + # add var explained
  theme_classic() +
  theme(axis.title =  element_text(size = 12),
        axis.text = element_text(size = 12),
        plot.subtitle = element_text(size = 12)) + 
  scale_x_discrete(labels = function(x) sapply(x, function(el) {
    if (el == "WRB") return("Soil type")
    else if (el == "Dominant_tree_type") return("Vegetation")
    else return(el)
  })) 
print(RF_TN_plot)

ggsave(paste0(Figure_path,"Figure1F_RF_TN_plot.pdf"),RF_TN_plot,width = 3,height = 4)

```


```{r Boxplot}
# Boxplot of pH.H2O. vs Vegetation
pHvsVeg_plot <- 
  ggplot(data = na.omit(data_base[c('Dominant_tree_type', 'pH.H2O.')]), aes(x = Dominant_tree_type, y = pH.H2O.)) +
  geom_boxplot(aes(fill = Dominant_tree_type)) + # Fill boxes based on Dominant_tree_type +
  geom_jitter(color = "black", width = 0.2, alpha = 0.5) + # Add jitter with specified color and transparency
  scale_fill_manual(values = c("Broadleaf" = "#52854C", "Conifer" = "#E7B800")) + # Custom colors for box fill
  theme_classic() + 
  theme(axis.title = element_text(size = 12), 
        axis.text = element_text(size = 12, angle = 30, hjust = 1),
        legend.position = "none") +
  labs(x = "Vegetation", y = "Soil habitat pH") + 
  scale_y_continuous(limits = c(3, 8.5)) + # Adjust the y-axis scale
  stat_compare_means(method = "kruskal.test", label.y = 8.2) # Perform and add statistical comparison
plot(pHvsVeg_plot)

ggsave(paste0(Figure_path,"Figure1C_Box_pH_plot.pdf"),pHvsVeg_plot,width = 3,height = 4)

# Boxplot of Total.C vs Soil Parent Material
TCvsSoil_plot <-   
  ggplot(data = na.omit(data_base[c('WRB', 'Total.C')]), aes(x = WRB, y = Total.C)) +
  geom_boxplot(aes(fill = WRB)) + 
  geom_jitter(color = "black", width = 0.2, alpha = 0.5) + 
  scale_fill_manual(values = c("Acrisols" = "gray", "Andosols" = "brown","Cambisols" = "#1f77b4", "Regosols" = "gray")) + 
  theme_classic() + 
  theme(axis.title = element_text(size = 12), 
        axis.text = element_text(size = 12, angle = 30, hjust = 1),
        legend.position = "none") +
  labs(x = "Soil type", y = "Soil C content (%)") + 
  scale_y_continuous(limits = c(0, 32)) + # Adjust the y-axis scale
  stat_compare_means(comparisons = list( c("Andosols", "Cambisols"), label.y = 23)) +
  stat_compare_means(method = "kruskal.test", label.y = 30) # Perform and add statistical comparison
plot(TCvsSoil_plot)

ggsave(paste0(Figure_path,"Figure1E_Box_TC_plot.pdf"),TCvsSoil_plot,width = 3,height = 4)

# Boxplot of Total.N vs Soil Parent Material
TNvsSoil_plot <-   
  ggplot(data = na.omit(data_base[c('WRB', 'Total.N')]), aes(x = WRB, y = Total.N)) +
  geom_boxplot(aes(fill = WRB)) + 
  geom_jitter(color = "black", width = 0.2, alpha = 0.5) + 
  scale_fill_manual(values = c("Acrisols" = "gray", "Andosols" = "brown","Cambisols" = "#1f77b4", "Regosols" = "gray")) + 
  theme_classic() + 
  theme(axis.title = element_text(size = 12), 
        axis.text = element_text(size = 12, angle = 30, hjust = 1),
        legend.position = "none") +
  labs(x = "Soil type", y = "Soil N content (%)") + 
  scale_y_continuous(limits = c(0, 1.8)) + # Adjust the y-axis scale
  stat_compare_means(comparisons = list( c("Andosols", "Cambisols"))) +
  stat_compare_means(method = "kruskal.test", label.y = 1.7) # Perform and add statistical comparison
plot(TNvsSoil_plot)

ggsave(paste0(Figure_path,"Figure1G_Box_TN_plot.pdf"),TNvsSoil_plot,width = 3,height = 4)

```

```{r save sub-figures of Figure1}
# Save
#ggsave(paste0(figure1_path, "/RF_pH_plot.png"), RF_pH_plot, width = 3.5, height = 4, dpi = 300)
#ggsave(paste0(figure1_path, "/RF_TC_plot.png"), RF_TC_plot, width = 3.5, height = 4, dpi = 300)
#ggsave(paste0(figure1_path, "/RF_TN_plot.png"), RF_TN_plot, width = 3.5, height = 4, dpi = 300)
#ggsave(paste0(figure1_path, "/pHvsVeg_plot.png"), pHvsVeg_plot, width = 3.5, height = 4, dpi = 300)
#ggsave(paste0(figure1_path, "/TCvsSoil_plot.png"), TCvsSoil_plot, width = 3.5, height = 4, dpi = 300)
#ggsave(paste0(figure1_path, "/TNvsSoil_plot.png"), TNvsSoil_plot, width = 3.5, height = 4, dpi = 300)
```